# Generated by Django 6.0.3 on 2026-04-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_seed_service_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'ordering': ['name']},
        ),
    ]
