# Generated by Django 6.0.3 on 2026-04-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image_url'),
    ]

    operations = [
    ]
