# Generated by Django 6.0.3 on 2026-04-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_noop_image_url'),
    ]

    operations = [
    ]
